apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao-deployment
spec:
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
      - name: api
        image: rodrigopontes/api-conversao:latest
        ports:
        - containerPort: 8080
